name: Deploy GitHub Pages
# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # 使用 JamesIves/github-pages-deploy-action@releases/v4 脚本需要的配置
          persist-credentials: false

      # 设置Node环境
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # 1、生成静态文件
      - name: Install And Build
        run: |
          npm install docsite -g 
          npm install 
          docsite build
          mkdir         ./dist/
          mv build      ./dist/
          mv en-us      ./dist/ 
          mv zh-cn      ./dist/ 
          mv img        ./dist/
          mv 404.html   ./dist/
          mv index.html ./dist/

      # 2、 复制到新分支
      # - name: Copy To Branches Action
      #   uses: planetoftheweb/copy-to-branches@v1
      #   env:
      #     # 来源分支
      #     key: master
      #     # 目标分支 branch1 branch2
      #     branches: site
      #     # 要复制的文件 folder1 file1
      #     files: en-us img md_json zh-cn 404.html index.html

      # 3、部署到 GitHub Pages
      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          # repository-name: lorchr/light-docs
          branch: site
          # npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`
          folder: dist

      # 4、同步到 gitee 的仓库
      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 注意在 Settings-> Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # 注意替换为你的 GitHub 源仓库地址
      #     source-repo: git@github.com:lorchr/light-docs.git
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:lorchr/light-docs.git
      
      # 5、部署到 Gitee Pages
      # - name: Build Gitee Pages
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     # 注意替换为你的 Gitee 用户名
      #     gitee-username: lorchr
      #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
      #     gitee-repo: lorchr/light-docs
      #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
      #     branch: site
      
      # 6、部署到 lorchr.top 服务器
      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@4.1
      #   with:
      #     # 这里是 rsync 的参数 switches: -avzh --delete --exclude="" --include="" --filter=""
      #     switches: -avzh
      #     path: public/
      #     remote_path: /home/ubuntu/public/
      #     remote_host: lorchr.top
      #     remote_port: 22
      #     remote_user: ubuntu
      #     remote_key: ${{ secrets.MY_UBUNTU_RSA_PRIVATE_KEY }}
